apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
  namespace: apps
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: "myapp-canary"
      stableService: "myapp-stable"
      trafficRouting:
        smi:
          rootService: myapp

      analysis:
        templates:
          - templateName: success-rate-analysis
        args:
          - name: service-name
            value: myapp-canary
          - name: from
            value: slow-cooker
      steps:
      - setWeight: 10
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 70
      - pause: {duration: 30s}
      - setWeight: 90
      - pause: {duration: 30s}
      - setWeight: 100
  selector:
    matchLabels:
     app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      # - name: myapp
      #   image: argoproj/rollouts-demo:blue
      #   imagePullPolicy: Always
      #   ports:
      #   - name: http
      #     containerPort: 8080
      #     protocol: TCP
      #   resources:
      #     requests:
      #       memory: 32Mi
      #       cpu: 5m
      - name: myapp
        image: ghcr.io/mccutchen/go-httpbin:2.17
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
